version: '3'
services:
  simulator:
    image: python:3.8
    container_name: simulator
    networks:
      - mynetwork
    volumes:
      - .:/app  # Mount the current directory into the container
    command: python /app/simulator.py

  processor:
    container_name: processor
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - spark-master
      - spark-worker  # Add spark-worker as a dependency
    networks:
      - mynetwork
    volumes:
      - .:/app  # Mount the current directory into the container
    environment:
      - SPARK_MASTER_HOST=spark-master
    command: spark-submit --master spark://spark-master:7077 /app/processor.py

  mongo:
    image: mongo:latest
    container_name: mongohost
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  spark-master:
    image: docker.io/bitnami/spark:3
    container_name: spark-master
    hostname: spark-master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    networks:
      - mynetwork

  spark-worker:
    image: docker.io/bitnami/spark:3
    container_name: spark-worker
    hostname: spark-worker
    user: root
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077  # Set the Spark master URL
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - mynetwork

networks:
  mynetwork: