name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the Python version you need
    
      - name: Install dependencies
        run: |
          pip install pytest 
          pip install beautifulsoup4 
          pip install pymongo 
    
      - name: Run tests
        run: |
          pytest test_processor.py