jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the Python version you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with your requirements file if needed

    - name: Run tests
      run: |
        pytest /app/test_processor.py  # Modify the path to your test file
